replicaCount: 2

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 14.5.0-debian-11-r13
  debug: true
  pullPolicy: IfNotPresent


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


global:
  postgresql:        
    auth:
      postgresPassword: abcd1234
postgresql:
  primary:  
    initdb:
      scripts:
        import_data.sh: |
          #!/bin/sh
          export PGPASSWORD=abcd1234
          echo "CREATE DATABASE dvdrental;" > /tmp/script.sq
          psql -U postgres -f /tmp/script.sq 
          curl -o /tmp/dvdrental.zip https://www.postgresqltutorial.com/wp-content/uploads/2019/05/dvdrental.zip
          gunzip -d -S .zip /tmp/dvdrental
          pg_restore -U postgres -d dvdrental /tmp/dvdrental          